
package com.founder.xmlconvert;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConvertHeaderServiceWS", targetNamespace = "xmlconvert.founder.com", wsdlLocation = "http://localhost:8080/xml-transform/ConvertHeaderService?wsdl")
public class ConvertHeaderServiceWS
    extends Service
{

    private final static URL CONVERTHEADERSERVICEWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.founder.xmlconvert.ConvertHeaderServiceWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.founder.xmlconvert.ConvertHeaderServiceWS.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/xml-transform/ConvertHeaderService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/xml-transform/ConvertHeaderService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONVERTHEADERSERVICEWS_WSDL_LOCATION = url;
    }

    public ConvertHeaderServiceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertHeaderServiceWS() {
        super(CONVERTHEADERSERVICEWS_WSDL_LOCATION, new QName("xmlconvert.founder.com", "ConvertHeaderServiceWS"));
    }

    /**
     * 
     * @return
     *     returns ConvertHeaderService
     */
    @WebEndpoint(name = "ConvertHeaderServicePort")
    public ConvertHeaderService getConvertHeaderServicePort() {
        return super.getPort(new QName("xmlconvert.founder.com", "ConvertHeaderServicePort"), ConvertHeaderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertHeaderService
     */
    @WebEndpoint(name = "ConvertHeaderServicePort")
    public ConvertHeaderService getConvertHeaderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("xmlconvert.founder.com", "ConvertHeaderServicePort"), ConvertHeaderService.class, features);
    }

}
