
package com.founder.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmrArchiveServicePortType", targetNamespace = "http://webservice.founder.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmrArchiveServicePortType {


    /**
     * 
     * @param args5
     * @param args6
     * @param args3
     * @param args4
     * @param args1
     * @param args2
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ArcUPFile", action = "urn:ArcUPFile")
    @WebResult(targetNamespace = "http://webservice.founder.com")
    @RequestWrapper(localName = "ArcUPFile", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArcUPFile")
    @ResponseWrapper(localName = "ArcUPFileResponse", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArcUPFileResponse")
    public String arcUPFile(
        @WebParam(name = "args0", targetNamespace = "http://webservice.founder.com")
        byte[] args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.founder.com")
        String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.founder.com")
        String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.founder.com")
        String args3,
        @WebParam(name = "args4", targetNamespace = "http://webservice.founder.com")
        String args4,
        @WebParam(name = "args5", targetNamespace = "http://webservice.founder.com")
        String args5,
        @WebParam(name = "args6", targetNamespace = "http://webservice.founder.com")
        String args6);

    /**
     * 
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ArcRelieveApply", action = "urn:ArcRelieveApply")
    @WebResult(targetNamespace = "http://webservice.founder.com")
    @RequestWrapper(localName = "ArcRelieveApply", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArcRelieveApply")
    @ResponseWrapper(localName = "ArcRelieveApplyResponse", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArcRelieveApplyResponse")
    public String arcRelieveApply(
        @WebParam(name = "args0", targetNamespace = "http://webservice.founder.com")
        String args0);

    /**
     * 
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ArcChkUser", action = "urn:ArcChkUser")
    @WebResult(targetNamespace = "http://webservice.founder.com")
    @RequestWrapper(localName = "ArcChkUser", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArcChkUser")
    @ResponseWrapper(localName = "ArcChkUserResponse", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArcChkUserResponse")
    public String arcChkUser(
        @WebParam(name = "args0", targetNamespace = "http://webservice.founder.com")
        String args0);

    /**
     * 
     * @param args1
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ArchiveYN", action = "urn:ArchiveYN")
    @WebResult(targetNamespace = "http://webservice.founder.com")
    @RequestWrapper(localName = "ArchiveYN", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArchiveYN")
    @ResponseWrapper(localName = "ArchiveYNResponse", targetNamespace = "http://webservice.founder.com", className = "com.founder.webservice.ArchiveYNResponse")
    public String archiveYN(
        @WebParam(name = "args0", targetNamespace = "http://webservice.founder.com")
        String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.founder.com")
        String args1);

}
