select
  RETRIEVAL_CD,
  RETRIEVAL_NM,
  OWN_TP_CD,
  DEPT_CD,
  RESPONSIBLE_CD,
  RETRIEVAL_KEY,
  STATUS_F,
  MEMO,
  SORT_NO,
  SPELL_NO,
  WUBI_NO,
  UPD_CNT,
  CRT_TIME,
  CRT_USER_ID,
  CRT_DEPT_CD,
  LAST_UPD_TIME,
  LAST_UPD_DEPT_CD,
  LAST_UPD_USER_ID,
  DEL_F
from
  IEMR_RETRIEVAL
where
  RETRIEVAL_CD = /* retrievalCd */'a'
and del_f = 0
